"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n*2ilgr4*qw42u-hs8p_#)da87bfh3sezu-)&l-@k00ul25%0o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'weather.apps.WeatherConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_apscheduler',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# OpenWeather API Configuration
OPENWEATHER_API_KEY = 'eeaadaf7379c64995f3d93198e192da1'  # Replace with your actual OpenWeather API key
OPENWEATHER_API_URL = 'https://api.openweathermap.org/data/2.5/weather'
WEATHER_UPDATE_INTERVAL_HOURS = 2  # Update weather every 2 hours
DEFAULT_WEATHER_CITY = 'Wuhan'  # Default city to fetch weather for
DEFAULT_WEATHER_COUNTRY = 'CN'   # Default country code

# LLM API Configuration (using OpenAI instead of Deepseek)
# OpenAI API settings
DEEPSEEK_API_KEY = 'sk-00e7089f276d46b1baad45c2335e4a3a'
DEEPSEEK_API_URL = 'https://api.deepseek.com'
DEEPSEEK_MODEL = 'deepseek-chat' 

# Characters for weather reports - you can customize these characters and their descriptions
WEATHER_CHARACTERS = [
    {
        'name': 'Eludecia the Succubus Paladin',
        'description': 'A reformed succubus who has pledged herself to a holy order, constantly balancing between her demonic nature and righteous path. She speaks with both seductive charm and noble virtue when discussing the weather.',
        'avatar_color': '#800080'
    }
]

# Default Character
DEFAULT_WEATHER_CHARACTER = 'Eludecia the Succubus Paladin'

# Cities for weather reports
DEFAULT_CITIES = [
    {'name': 'Shanghai', 'country': 'CN'},
    {'name': 'Wuhan', 'country': 'CN'},
    {'name': 'Sydney', 'country': 'AU'}
]

# Weather app settings
WEATHER_PAGINATION_PER_PAGE = 6  # Number of weather cards to show per page
WEATHER_COMMENTS_PER_PAGE = 5    # Number of comments to show initially (others are paginated)
