# Generated by Django 5.2 on 2025-04-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weather',
            new_name='Weather_current',
        ),
    ]
