# Generated by Django 5.2 on 2025-04-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_rename_weather_weather_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather_current',
            name='character_letter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weather_current',
            name='character_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
